/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra20_2014_taskmanager_NativeClass */

#ifndef _Included_ra20_2014_taskmanager_NativeClass
#define _Included_ra20_2014_taskmanager_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra20_2014_taskmanager_NativeClass
 * Method:    calculatePercent
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ra20_12014_taskmanager_NativeClass_calculatePercent
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
